/*
-- Query: select * from `nozama`.`product`
LIMIT 0, 1000

-- Date: 2016-03-03 12:57
*/
INSERT INTO `product` (`id_product`,`name`,`name_tag_date_released`,`description`,`url_picture`,`date_released`) VALUES (5,'Forrest Gump','forest-gump-1994','Quelques décennies d\'histoire américaine, des années 1940 à la fin du XXème siècle, à travers le regard et l\'étrange odyssée d\'un homme simple et pur, Forrest Gump.','forrest-gump.jpg','1994-09-04');
INSERT INTO `product` (`id_product`,`name`,`name_tag_date_released`,`description`,`url_picture`,`date_released`) VALUES (6,'La Ligne Verte','la-ligne-verte-2000','Paul Edgecomb, Gardien-chef du pénitencier de Cold Mountain en 1935, était chargé de veiller au bon déroulement des exécutions capitales. Parmi les prisonniers se trouvait un colosse du nom de John Coffey...','La-Ligne-Verte.jpg','2000-03-01');
INSERT INTO `product` (`id_product`,`name`,`name_tag_date_released`,`description`,`url_picture`,`date_released`) VALUES (7,'Django Unchained','django-unchained-2013','Le parcours d\'un chasseur de prime allemand et d\'un homme noir pour retrouver la femme de ce dernier retenue en esclavage par le propriétaire d\'une plantation...','Django-Unchained.jpg','2013-01-16');
INSERT INTO `product` (`id_product`,`name`,`name_tag_date_released`,`description`,`url_picture`,`date_released`) VALUES (8,'Gran Torino','gran-torino-2009','Walt Kowalski est un ancien de la guerre de Corée, un homme inflexible, amer et pétri de préjugés surannés. Hormis sa chienne Daisy, il ne fait confiance qu\'à son M-1, toujours propre, toujours prêt à l\'usage...','Gran-Torino.jpg','2009-02-25');
INSERT INTO `product` (`id_product`,`name`,`name_tag_date_released`,`description`,`url_picture`,`date_released`) VALUES (9,'La Liste de Schindler','la-liste-de-schindler-1994','Evocation des années de guerre d\'Oskar Schindler, industriel autrichien rentré à Cracovie en 1939 avec les troupes allemandes. Il va, tout au long de la guerre, protéger des juifs en les faisant travailler dans sa fabrique.','La-Liste-de-Schindler.jpg','1994-03-02');
INSERT INTO `product` (`id_product`,`name`,`name_tag_date_released`,`description`,`url_picture`,`date_released`) VALUES (10,'The Dark Knight, Le Chevalier Noir','the-dark-knight-le-chevalier-noir-2008','Batman entreprend de démanteler les dernières organisations criminelles de Gotham. Mais il se heurte bientôt à un nouveau génie du crime qui répand la terreur et le chaos dans la ville : le Joker...','The-Dark-Knight-Le-Chevalier-Noir.jpg','2008-08-13');
INSERT INTO `product` (`id_product`,`name`,`name_tag_date_released`,`description`,`url_picture`,`date_released`) VALUES (11,'Le Parrain','le-parrain-1972','En 1945, à New York, les Corleone sont une des cinq familles de la mafia. Don Vito Corleone marie sa fille à un bookmaker. Sollozzo, \"parrain\" de la famille Tattaglia, propose à Don Vito une association dans le trafic de drogue...','Le-Parrain.jpg','1972-03-25');
INSERT INTO `product` (`id_product`,`name`,`name_tag_date_released`,`description`,`url_picture`,`date_released`) VALUES (12,'Pulp Fiction','pulp-fiction-1994','L\'odyssée sanglante et burlesque de petits malfrats dans la jungle de Hollywood à travers trois histoires qui s\'entremêlent.','pulp_fiction.jpg','1994-10-26');
INSERT INTO `product` (`id_product`,`name`,`name_tag_date_released`,`description`,`url_picture`,`date_released`) VALUES (13,'Fight Club','fight-club-1999','Le narrateur, vit seul, travaille seul, dort seul, comme beaucoup d\'autres personnes seules qui connaissent la misère morale et sexuelle. C\'est pourquoi il va devenir membre du Fight club, un lieu clandestin dirigé par Tyler Durden, anarchiste entre gourou et philosophe.','Fight-Club.jpg','1999-11-10');
INSERT INTO `product` (`id_product`,`name`,`name_tag_date_released`,`description`,`url_picture`,`date_released`) VALUES (14,'Mommy','mommy-2014','Une veuve mono-parentale hérite de la garde de son fils, un adolescent profondément turbulent. Ensemble, ils tentent de joindre les deux bouts, notamment grâce à l’aide inattendue de la mystérieuse voisine d’en face, Kyla.','mommy.jpg','2014-10-08');
INSERT INTO `product` (`id_product`,`name`,`name_tag_date_released`,`description`,`url_picture`,`date_released`) VALUES (15,'Intouchables','intouchables-2011','La rencontre improbable, touchante et drôle entre un riche aristocrate, tétraplégique depuis un accident de parapente, et un jeune de banlieue engagé par hasard pour être son aide à domicile...','intouchable.jpg','2011-11-02');
INSERT INTO `product` (`id_product`,`name`,`name_tag_date_released`,`description`,`url_picture`,`date_released`) VALUES (16,'Le Roi Lion','le-roi-lion-1994','Le long combat de Simba le lionceau pour accéder à son rang de roi des animaux, après que le fourbe Scar, son oncle, ait tué son père et pris sa place.','le-roi-lion.jpg','1994-11-23');
INSERT INTO `product` (`id_product`,`name`,`name_tag_date_released`,`description`,`url_picture`,`date_released`) VALUES (17,'Interstellar','interstellar-2014','Le film raconte les aventures d’un groupe d’explorateurs qui utilisent une faille récemment découverte dans l’espace-temps afin de repousser les limites humaines et partir à la conquête des distances astronomiques dans un voyage interstellaire.','Interstellar.jpg','2014-11-05');
INSERT INTO `product` (`id_product`,`name`,`name_tag_date_released`,`description`,`url_picture`,`date_released`) VALUES (18,'To Pimp a Butterfly','to-pimp-a-butterfly-2015','Les meilleurs albums des années 2010. Les meilleurs albums de rap US. Les meilleurs albums de rap. Les meilleurs albums californiens','kendrick-lamar-butterflu.jpg','2015-05-17');
INSERT INTO `product` (`id_product`,`name`,`name_tag_date_released`,`description`,`url_picture`,`date_released`) VALUES (19,'Nevermind','nevermind-1991','Album de Nirvana','nirvana-nevermind.jpg','1991-01-01');
INSERT INTO `product` (`id_product`,`name`,`name_tag_date_released`,`description`,`url_picture`,`date_released`) VALUES (20,'[Led Zeppelin IV]','led-zeppelin-vi-1971','Album de Led Zeppelin','led_zeppelin_led_zeppelin_iv.jpg','1991-01-01');
INSERT INTO `product` (`id_product`,`name`,`name_tag_date_released`,`description`,`url_picture`,`date_released`) VALUES (21,'Sgt. Pepper’s Lonely Hearts Club Band','peppers-lonely-hearts-club-band-1967','Album de The Beatles','beatles.jpg','1967-01-01');
INSERT INTO `product` (`id_product`,`name`,`name_tag_date_released`,`description`,`url_picture`,`date_released`) VALUES (22,'Thriller','thriller-1982','Album de Michael Jackson','Michael_Jackson-Thriller.jpg','1982-01-01');
INSERT INTO `product` (`id_product`,`name`,`name_tag_date_released`,`description`,`url_picture`,`date_released`) VALUES (23,'Dark Side of the Moon','dark-side-of-the-moon-1973','Album de Pink Floyd','Dark_Side_of_the_Moon.png','1973-01-01');
INSERT INTO `product` (`id_product`,`name`,`name_tag_date_released`,`description`,`url_picture`,`date_released`) VALUES (24,'Back in Black','back-in-black-1980','Album de AC/DC','maxresdefault.jpg','1980-01-01');
INSERT INTO `product` (`id_product`,`name`,`name_tag_date_released`,`description`,`url_picture`,`date_released`) VALUES (25,'The Princess','the-princess-2012','Album de Parov Stelar','princess.jpg','2012-04-20');
INSERT INTO `product` (`id_product`,`name`,`name_tag_date_released`,`description`,`url_picture`,`date_released`) VALUES (26,'Legend','legend-1984','Album de Bob Marley','bob-marley-legend.jpg','1984-05-08');
INSERT INTO `product` (`id_product`,`name`,`name_tag_date_released`,`description`,`url_picture`,`date_released`) VALUES (27,'Dragostea din tei','dragostea-din-tei-2004','Single de O-Zone','41WTZWTQQ2L.jpg','2004-01-01');
INSERT INTO `product` (`id_product`,`name`,`name_tag_date_released`,`description`,`url_picture`,`date_released`) VALUES (28,'Aserejé','asereje-2002','Single de Las Ketchup','The_Ketchup_Song_Asereje_Single.jpg','2002-01-01');
INSERT INTO `product` (`id_product`,`name`,`name_tag_date_released`,`description`,`url_picture`,`date_released`) VALUES (29,'Stan','Stan-2000','Single de Eminem featuring Dido','Eminem.jpg','2000-01-01');
INSERT INTO `product` (`id_product`,`name`,`name_tag_date_released`,`description`,`url_picture`,`date_released`) VALUES (30,'Oops!... I Did It Again','oops-i-did-it-again-2000','Single de Britney Spears','Oops.jpg','2000-01-01');
