package nozama.model;
// Generated 25 f�vr. 2016 15:17:06 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Album generated by hbm2java
 */
@Entity
@Table(name = "album", catalog = "nozama")
public class Album implements java.io.Serializable {

	private Integer idAlbum;
	private Artiste artiste;
	private Product product;
	private Date dateReleased;
	private String type;
	private Set<TypeSupportAlbum> typeSupportAlbums = new HashSet<TypeSupportAlbum>(0);
	private Set<AlbumHasSingle> albumHasSingles = new HashSet<AlbumHasSingle>(0);

	public Album() {
	}

	public Album(Artiste artiste, Product product) {
		this.artiste = artiste;
		this.product = product;
	}

	public Album(Artiste artiste, Product product, Date dateReleased, String type, Set<TypeSupportAlbum> typeSupportAlbums, Set<AlbumHasSingle> albumHasSingles) {
		this.artiste = artiste;
		this.product = product;
		this.dateReleased = dateReleased;
		this.type = type;
		this.typeSupportAlbums = typeSupportAlbums;
		this.albumHasSingles = albumHasSingles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_album", unique = true, nullable = false)
	public Integer getIdAlbum() {
		return this.idAlbum;
	}

	public void setIdAlbum(Integer idAlbum) {
		this.idAlbum = idAlbum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_artiste", nullable = false)
	public Artiste getArtiste() {
		return this.artiste;
	}

	public void setArtiste(Artiste artiste) {
		this.artiste = artiste;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_product", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_released", length = 10)
	public Date getDateReleased() {
		return this.dateReleased;
	}

	public void setDateReleased(Date dateReleased) {
		this.dateReleased = dateReleased;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "album")
	public Set<TypeSupportAlbum> getTypeSupportAlbums() {
		return this.typeSupportAlbums;
	}

	public void setTypeSupportAlbums(Set<TypeSupportAlbum> typeSupportAlbums) {
		this.typeSupportAlbums = typeSupportAlbums;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "album")
	public Set<AlbumHasSingle> getAlbumHasSingles() {
		return this.albumHasSingles;
	}

	public void setAlbumHasSingles(Set<AlbumHasSingle> albumHasSingles) {
		this.albumHasSingles = albumHasSingles;
	}

}
