package nozama.model;
// Generated 29 f�vr. 2016 19:25:52 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AlbumHasSingle generated by hbm2java
 */
@Entity
@Table(name = "album_has_single", catalog = "nozama")
public class AlbumHasSingle implements java.io.Serializable {

	private Integer idAlbumHasSingle;
	private Album album;
	private Single single;

	public AlbumHasSingle() {
	}

	public AlbumHasSingle(Album album, Single single) {
		this.album = album;
		this.single = single;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_album_has_single", unique = true, nullable = false)
	public Integer getIdAlbumHasSingle() {
		return this.idAlbumHasSingle;
	}

	public void setIdAlbumHasSingle(Integer idAlbumHasSingle) {
		this.idAlbumHasSingle = idAlbumHasSingle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_album", nullable = false)
	public Album getAlbum() {
		return this.album;
	}

	public void setAlbum(Album album) {
		this.album = album;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_single", nullable = false)
	public Single getSingle() {
		return this.single;
	}

	public void setSingle(Single single) {
		this.single = single;
	}

}
