package nozama.model;
// Generated 20 mars 2016 15:42:18 by Hibernate Tools 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Artiste generated by hbm2java
 */
@Entity
@Table(name = "artiste", catalog = "nozama")
public class Artiste implements java.io.Serializable {


  /**
   * 
   */
  private static final long serialVersionUID = 1L;
  private Integer idArtiste;
  private Product product;
  private String name;

  public Artiste() {}

  public Artiste(Product product, String name) {
    this.product = product;
    this.name = name;
  }

  @Id
  @GeneratedValue(strategy = IDENTITY)


  @Column(name = "id_artiste", unique = true, nullable = false)
  public Integer getIdArtiste() {
    return this.idArtiste;
  }

  public void setIdArtiste(Integer idArtiste) {
    this.idArtiste = idArtiste;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "id_product", nullable = false)
  public Product getProduct() {
    return this.product;
  }

  public void setProduct(Product product) {
    this.product = product;
  }


  @Column(name = "name", nullable = false)
  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }



}


