package nozama.model;
// Generated 29 f�vr. 2016 19:25:52 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "nozama", uniqueConstraints = @UniqueConstraint(columnNames = "name_tag_date_released") )
public class Product implements java.io.Serializable {

	private Integer idProduct;
	private String name;
	private String nameTagDateReleased;
	private String description;
	private String urlPicture;
	private Date dateReleased;
	private Set<Movie> movies = new HashSet<Movie>(0);
	private Set<Album> albums = new HashSet<Album>(0);
	private Set<Single> singles = new HashSet<Single>(0);

	public Product() {
	}

	public Product(String name, String nameTagDateReleased, String urlPicture, Date dateReleased) {
		this.name = name;
		this.nameTagDateReleased = nameTagDateReleased;
		this.urlPicture = urlPicture;
		this.dateReleased = dateReleased;
	}

	public Product(String name, String nameTagDateReleased, String description, String urlPicture, Date dateReleased, Set<Movie> movies, Set<Album> albums, Set<Single> singles) {
		this.name = name;
		this.nameTagDateReleased = nameTagDateReleased;
		this.description = description;
		this.urlPicture = urlPicture;
		this.dateReleased = dateReleased;
		this.movies = movies;
		this.albums = albums;
		this.singles = singles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_product", unique = true, nullable = false)
	public Integer getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(Integer idProduct) {
		this.idProduct = idProduct;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "name_tag_date_released", unique = true, nullable = false)
	public String getNameTagDateReleased() {
		return this.nameTagDateReleased;
	}

	public void setNameTagDateReleased(String nameTagDateReleased) {
		this.nameTagDateReleased = nameTagDateReleased;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "url_picture", nullable = false, length = 1024)
	public String getUrlPicture() {
		return this.urlPicture;
	}

	public void setUrlPicture(String urlPicture) {
		this.urlPicture = urlPicture;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_released", nullable = false, length = 10)
	public Date getDateReleased() {
		return this.dateReleased;
	}

	public void setDateReleased(Date dateReleased) {
		this.dateReleased = dateReleased;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Movie> getMovies() {
		return this.movies;
	}

	public void setMovies(Set<Movie> movies) {
		this.movies = movies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Album> getAlbums() {
		return this.albums;
	}

	public void setAlbums(Set<Album> albums) {
		this.albums = albums;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Single> getSingles() {
		return this.singles;
	}

	public void setSingles(Set<Single> singles) {
		this.singles = singles;
	}


}
