package nozama.model;
// Generated 21 mars 2016 08:24:02 by Hibernate Tools 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductOrder generated by hbm2java
 */
@Entity
@Table(name = "product_order", catalog = "nozama")
public class ProductOrder implements java.io.Serializable {


  private Integer idProductOrder;
  private Article article;
  private Order order;
  private int quantity;

  public ProductOrder() {}

  public ProductOrder(Article article, Order order, int quantity) {
    this.article = article;
    this.order = order;
    this.quantity = quantity;
  }

  @Id
  @GeneratedValue(strategy = IDENTITY)


  @Column(name = "id_product_order", unique = true, nullable = false)
  public Integer getIdProductOrder() {
    return this.idProductOrder;
  }

  public void setIdProductOrder(Integer idProductOrder) {
    this.idProductOrder = idProductOrder;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "id_article", nullable = false)
  public Article getArticle() {
    return this.article;
  }

  public void setArticle(Article article) {
    this.article = article;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "id_order", nullable = false)
  public Order getOrder() {
    return this.order;
  }

  public void setOrder(Order order) {
    this.order = order;
  }


  @Column(name = "quantity", nullable = false)
  public int getQuantity() {
    return this.quantity;
  }

  public void setQuantity(int quantity) {
    this.quantity = quantity;
  }



}


