package nozama.model;
// Generated 29 f�vr. 2016 19:25:52 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TypeSupportMovie generated by hbm2java
 */
@Entity
@Table(name = "type_support_movie", catalog = "nozama")
public class TypeSupportMovie implements java.io.Serializable,TypeSupport {

	private Integer idTypeSupport;
	private Movie movie;
	private String nameSupport;
	private int price;

	public TypeSupportMovie() {
	}

	public TypeSupportMovie(Movie movie, String nameSupport, int price) {
		this.movie = movie;
		this.nameSupport = nameSupport;
		this.price = price;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_type_support", unique = true, nullable = false)
	public Integer getIdTypeSupport() {
		return this.idTypeSupport;
	}

	public void setIdTypeSupport(Integer idTypeSupport) {
		this.idTypeSupport = idTypeSupport;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_movie", nullable = false)
	public Movie getMovie() {
		return this.movie;
	}

	public void setMovie(Movie movie) {
		this.movie = movie;
	}

	@Column(name = "name_support", nullable = false, length = 45)
	public String getNameSupport() {
		return this.nameSupport;
	}

	public void setNameSupport(String nameSupport) {
		this.nameSupport = nameSupport;
	}

	@Column(name = "price", nullable = false)
	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

}
