package nozama.model;
// Generated 25 f�vr. 2016 15:17:06 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TypeSupportSingle generated by hbm2java
 */
@Entity
@Table(name = "type_support_single", catalog = "nozama")
public class TypeSupportSingle implements java.io.Serializable {

	private Integer idTypeSupport;
	private Single single;
	private String nameSupport;
	private Integer price;

	public TypeSupportSingle() {
	}

	public TypeSupportSingle(Single single) {
		this.single = single;
	}

	public TypeSupportSingle(Single single, String nameSupport, Integer price) {
		this.single = single;
		this.nameSupport = nameSupport;
		this.price = price;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_type_support", unique = true, nullable = false)
	public Integer getIdTypeSupport() {
		return this.idTypeSupport;
	}

	public void setIdTypeSupport(Integer idTypeSupport) {
		this.idTypeSupport = idTypeSupport;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_single", nullable = false)
	public Single getSingle() {
		return this.single;
	}

	public void setSingle(Single single) {
		this.single = single;
	}

	@Column(name = "name_support", length = 45)
	public String getNameSupport() {
		return this.nameSupport;
	}

	public void setNameSupport(String nameSupport) {
		this.nameSupport = nameSupport;
	}

	@Column(name = "price")
	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

}
